export interface RoomType {
  id: string;
  name: string;
  size: string;
  view: string;
  beds: string;
  bathrooms: number;
  price: number;
  originalPrice?: number;
  maxGuests: number;
  amenities: string[];
  description: string;
  images: string[];
}

export interface Hotel {
  id: string;
  slug: string;
  name: string;
  shortName: string;
  type: 'city' | 'resort' | 'villa' | 'suites' | 'apartment';
  badge: string;
  city: string;
  state: string;
  address: string;
  phone: string;
  mapsLink: string;
  mapEmbed: string;
  rating: number;
  reviews: number;
  description: string;
  longDescription: string;
  checkIn: string;
  checkOut: string;
  highlights: string[];
  amenities: string[];
  rooms: RoomType[];
  images: string[];
  featured: boolean;
}

export const HOTELS: Hotel[] = [
  {
    id: '1',
    slug: 'tirupati',
    name: 'Hotel Southern Suites Tirupati',
    shortName: 'Tirupati',
    type: 'city',
    badge: 'Pilgrimage City',
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    address: '19-9-28/H10, 1, Tiruchanoor Rd, near Ramanuja Circle, Lakshmi Puram, Korramenugunta, Tirupati, Andhra Pradesh 517501',
    phone: '08125393888',
    mapsLink: 'https://maps.app.goo.gl/H5tCWVMa5E3CdZEi7',
    mapEmbed: 'https://maps.google.com/maps?q=Hotel+Southern+Suites+Tirupati&output=embed',
    rating: 4.1,
    reviews: 983,
    description: 'Located close to the city\'s major transit hubs, offering a perfect blend of traditional hospitality and modern facilities.',
    longDescription: 'Located close to the city\'s major transit hubs, Southern Suites Hotel Tirupati offers a perfect blend of traditional hospitality and modern facilities delivering a comfortable and pleasant stay experience. Only 19.6 km to Srivari Mettu. Free parking, airport and railway transfers, wheelchair accessible, doctor on call.',
    checkIn: '12:00 PM',
    checkOut: '11:00 AM',
    highlights: ['19.6 km to Srivari Mettu', 'Free Parking', 'Airport & Railway Transfers', 'Wheelchair Accessible', 'Doctor on Call', 'Shuttle Service'],
    amenities: ['Wi-Fi', 'Room Service', 'Elevator/Lift', 'Newspaper', 'Laundry Service', 'Concierge', 'Wheelchair', 'Multilingual Staff', 'Luggage Assistance', 'Doctor on Call', 'Meditation Room', 'Activity Centre', 'Shuttle Service', 'Airport Transfers', 'Hairdryer', 'Minibar', 'Iron/Ironing Board', 'Work Desk', 'CCTV', 'Security Guard', 'Lounge', 'Sun Deck', 'Balcony/Terrace', 'Prayer Room'],
    rooms: [
      {
        id: 'tip-001',
        name: 'Premium Room (AC)',
        size: '250 sq.ft (23 sq.mt)',
        view: 'Mountain/Hill View',
        beds: '1 King Bed',
        bathrooms: 1,
        price: 2171,
        originalPrice: 2500,
        maxGuests: 2,
        amenities: ['Iron/Ironing Board', 'Mineral Water', 'Air Conditioning', 'Work Desk', 'Chair', 'Closet', 'Telephone', 'Kettle', 'Safe', 'TV', 'Hairdryer', 'Hot & Cold Water', 'Toiletries', 'Towels', 'Peep Hole'],
        description: 'Comfortable AC room with mountain view, king bed and all modern amenities.',
        images: ['/images/hotels/tirupati/room1.jpg'],
      },
      {
        id: 'tip-002',
        name: 'Premium 2BHK Apartment (AC)',
        size: '21528 sq.ft (2000 sq.mt)',
        view: 'Mountain/Hill View',
        beds: '2 King Beds or 1 Single Bed',
        bathrooms: 2,
        price: 4341,
        originalPrice: 5000,
        maxGuests: 4,
        amenities: ['Iron/Ironing Board', 'Mineral Water', 'Air Conditioning', 'Minibar', 'Work Desk', 'Chair', 'Closet', 'Telephone', 'Kettle', 'Electronic Safe', 'TV', 'Hairdryer', 'Hot & Cold Water', 'Toiletries', 'Towels'],
        description: 'Spacious 2BHK apartment with mountain views, perfect for families.',
        images: ['/images/hotels/tirupati/room2.jpg'],
      },
    ],
    images: ['/images/hotels/tirupati/hotel1.jpg', '/images/hotels/tirupati/hotel2.jpg'],
    featured: true,
  },
  {
    id: '2',
    slug: 'nellore',
    name: 'Hotel Southern Suites Nellore',
    shortName: 'Nellore',
    type: 'city',
    badge: 'City Hotel',
    city: 'Nellore',
    state: 'Andhra Pradesh',
    address: 'BACK SIDE OF ENEL HOSPITAL, PVR, opp. ROAD JANATHA TILE, Magunta Layout, Nellore, Andhra Pradesh 524004',
    phone: '08612372901',
    mapsLink: 'https://maps.app.goo.gl/LVYXzy8YeMWaGPR4A',
    mapEmbed: 'https://maps.google.com/maps?q=Hotel+Southern+Suites+Nellore&output=embed',
    rating: 3.9,
    reviews: 420,
    description: 'A premium stay with service apartment-style amenities in the heart of Nellore.',
    longDescription: 'Hotel Southern Suites Nellore offers a premium service apartment experience with full kitchen facilities, study rooms, and a comprehensive list of amenities including BBQ, air purification, and in-room dining. Located in Magunta Layout, close to major landmarks.',
    checkIn: '12:00 PM',
    checkOut: '11:00 AM',
    highlights: ['Full Kitchen', 'BBQ Grill', 'Air Purifier', 'Study Room', 'Cook & Butler Service', 'Balcony'],
    amenities: ['Study Room', 'Iron/Ironing Board', 'Air Purifier', 'Mineral Water', 'Housekeeping', 'In-room Dining', 'Air Conditioning', 'Room Service', 'Heater', 'Wi-Fi', 'Minibar', 'Mini Fridge', 'Coffee Machine', 'BBQ Grill', 'Cook & Butler Service', 'Safe', 'Washing Machine', 'Dishwasher', 'Refrigerator', 'Smart Controls', 'Speakers', 'TV', 'Balcony', 'Terrace'],
    rooms: [
      {
        id: 'nel-001',
        name: 'Deluxe Service Apartment',
        size: '256 sq.ft (24 sq.mt)',
        view: 'City View',
        beds: '1 King Bed',
        bathrooms: 1,
        price: 1200,
        originalPrice: 1500,
        maxGuests: 2,
        amenities: ['Study Room', 'Air Purifier', 'Iron/Ironing Board', 'Mineral Water', 'Air Conditioning', 'Wi-Fi', 'Minibar', 'Mini Fridge', 'Coffee Machine', 'BBQ Grill', 'Safe', 'TV', 'Balcony', 'Western Toilet', 'Hot & Cold Water', 'Toiletries', 'Towels'],
        description: 'Spacious service apartment with full kitchen and all home-like amenities.',
        images: ['/images/hotels/nellore/room1.jpg'],
      },
    ],
    images: ['/images/hotels/nellore/hotel1.jpg', '/images/hotels/nellore/hotel2.jpg'],
    featured: false,
  },
  {
    id: '3',
    slug: 'kakinada',
    name: 'Hotel Southern Suites Kakinada',
    shortName: 'Kakinada',
    type: 'city',
    badge: 'City Hotel',
    city: 'Kakinada',
    state: 'Andhra Pradesh',
    address: 'D;No;9, 434, 1st Right Lane, opposite SRMT Mall, Muralidhar Nagar, Ramanayapeta, Ramanayyapeta, Andhra Pradesh 533005',
    phone: '09515614666',
    mapsLink: 'https://maps.app.goo.gl/2hBnUox4ZdFa5DyH6',
    mapEmbed: 'https://maps.google.com/maps?q=Hotel+Southern+Suites+Kakinada&output=embed',
    rating: 4.0,
    reviews: 310,
    description: 'Premium AC rooms opposite SRMT Mall in the heart of Kakinada.',
    longDescription: 'Hotel Southern Suites Kakinada offers executive AC rooms with city views, located opposite SRMT Mall in Muralidhar Nagar. All rooms feature king beds, private bath with shower cubicle, minibar, and complete amenities.',
    checkIn: '12:00 PM',
    checkOut: '11:00 AM',
    highlights: ['Opposite SRMT Mall', 'AC Rooms', 'King Bed', 'Minibar', 'City View', '24hr Reception'],
    amenities: ['Air Conditioning', 'Wi-Fi', 'Mineral Water', 'Iron/Ironing Board', 'Minibar', 'Work Desk', 'Chair', 'Closet', 'Telephone', 'Kettle', 'Safe', 'TV', 'Hairdryer', 'Shaving Mirror', 'Dental Kit', 'Hot & Cold Water', 'Toiletries', 'Shower Cubicle', 'Jetspray'],
    rooms: [
      {
        id: 'kak-001',
        name: 'Executive Room',
        size: '225 sq.ft (21 sq.mt)',
        view: 'City View',
        beds: '1 King Bed',
        bathrooms: 1,
        price: 1200,
        originalPrice: 1500,
        maxGuests: 2,
        amenities: ['Mineral Water', 'Iron/Ironing Board', 'Wi-Fi', 'Minibar', 'Work Desk', 'Closet', 'Telephone', 'Kettle', 'Safe', 'TV', 'Hairdryer', 'Shaving Mirror', 'Dental Kit', 'Hot & Cold Water', 'Toiletries', 'Shower Cubicle', 'Jetspray'],
        description: 'Executive AC room with king bed and city view.',
        images: ['/images/hotels/kakinada/room1.jpg'],
      },
    ],
    images: ['/images/hotels/kakinada/hotel1.jpg'],
    featured: false,
  },
  {
    id: '4',
    slug: 'vijayawada',
    name: 'Hotel Southern Suites Vijayawada',
    shortName: 'Vijayawada',
    type: 'city',
    badge: 'City Hotel',
    city: 'Vijayawada',
    state: 'Andhra Pradesh',
    address: 'KSN Complex, D.No: 74-1-8, MG Rd, opp. RTC Bus Stand, Patamata, Vijayawada, Andhra Pradesh 520007',
    phone: '07993986633',
    mapsLink: 'https://maps.app.goo.gl/RwsPHuLpPHGDK47WA',
    mapEmbed: 'https://maps.google.com/maps?q=Hotel+Southern+Suites+Vijayawada&output=embed',
    rating: 4.0,
    reviews: 280,
    description: 'Prime location opposite RTC Bus Stand on MG Road, Vijayawada.',
    longDescription: 'Hotel Southern Suites Vijayawada sits in the prime KSN Complex on MG Road, directly opposite the RTC Bus Stand. Offering superior rooms with king and twin bed configurations, ideal for business and leisure travellers.',
    checkIn: '12:00 PM',
    checkOut: '11:00 AM',
    highlights: ['Opposite RTC Bus Stand', 'MG Road Location', 'Superior Rooms', 'King & Twin Beds', 'AC Rooms', 'City View'],
    amenities: ['Air Conditioning', 'Wi-Fi', 'Room Service', 'Elevator/Lift', 'Housekeeping', 'Luggage Assistance', 'CCTV', 'Reception 24hr', 'Mineral Water', 'TV', 'Hot & Cold Water', 'Toiletries'],
    rooms: [
      {
        id: 'vjw-001',
        name: 'Superior Room - King Bed',
        size: '250 sq.ft',
        view: 'City View',
        beds: '1 King Bed',
        bathrooms: 1,
        price: 1804,
        originalPrice: 2100,
        maxGuests: 2,
        amenities: ['Air Conditioning', 'Wi-Fi', 'TV', 'Mineral Water', 'Hot & Cold Water', 'Toiletries', 'Housekeeping'],
        description: 'Superior room with king bed and city view.',
        images: ['/images/hotels/vijayawada/room1.jpg'],
      },
      {
        id: 'vjw-002',
        name: 'Superior Twin Beds Room',
        size: '250 sq.ft',
        view: 'City View',
        beds: '2 Single Beds',
        bathrooms: 1,
        price: 1855,
        originalPrice: 2150,
        maxGuests: 2,
        amenities: ['Air Conditioning', 'Wi-Fi', 'TV', 'Mineral Water', 'Hot & Cold Water', 'Toiletries', 'Housekeeping'],
        description: 'Superior room with two single beds, perfect for colleagues or friends.',
        images: ['/images/hotels/vijayawada/room2.jpg'],
      },
    ],
    images: ['/images/hotels/vijayawada/hotel1.jpg'],
    featured: false,
  },
  {
    id: '5',
    slug: 'hyderabad',
    name: 'Hotel Southern Suites Hyderabad',
    shortName: 'Hyderabad',
    type: 'city',
    badge: 'City Hotel',
    city: 'Hyderabad',
    state: 'Telangana',
    address: 'MIG-II, 175, Kukatpally Housing Board Colony, K P H B Phase 9, Kukatpally, Hyderabad, Telangana 500085',
    phone: '+919618138686',
    mapsLink: 'https://maps.app.goo.gl/xZgxNMMjc3ivqfnRA',
    mapEmbed: 'https://maps.google.com/maps?q=Hotel+Southern+Suites+Hyderabad+Kukatpally&output=embed',
    rating: 4.0,
    reviews: 520,
    description: 'Modern executive rooms near Nexus Hyderabad Mall in Kukatpally.',
    longDescription: 'Hotel Southern Suites Hyderabad is located in the KPHB Colony, Kukatpally — a minute\'s walk from Nexus Hyderabad Mall. Features executive rooms with king beds, city views, complete business amenities, power backup, and 24-hour reception.',
    checkIn: '12:00 PM',
    checkOut: '11:00 AM',
    highlights: ['Near Nexus Mall', 'Power Backup', 'Elevator/Lift', 'Housekeeping', 'Room Service', 'Wheelchair Access'],
    amenities: ['Room Service', 'Power Backup', 'Elevator/Lift', 'Housekeeping', 'Air Conditioning', 'Luggage Assistance', 'Wheelchair', 'Hairdryer', 'Iron/Ironing Board', 'Mineral Water', 'Toiletries', 'CCTV', 'Reception 24hr', 'Wi-Fi', 'TV', 'Kettle', 'Hot & Cold Water', 'Towels'],
    rooms: [
      {
        id: 'hyd-001',
        name: 'Executive Room',
        size: '250 sq.ft (23 sq.mt)',
        view: 'City View',
        beds: '1 King Bed',
        bathrooms: 1,
        price: 1860,
        originalPrice: 2000,
        maxGuests: 2,
        amenities: ['Iron/Ironing Board', 'Air Conditioning', 'Wi-Fi', 'Mineral Water', 'TV', 'Hairdryer', 'Hot & Cold Water', 'Toiletries', 'Towels', 'Kettle'],
        description: 'City-view executive room with king bed, 250 sq.ft of comfort.',
        images: ['/images/hotels/hyderabad/room1.jpg'],
      },
    ],
    images: ['/images/hotels/hyderabad/hotel1.jpg', '/images/hotels/hyderabad/hotel2.jpg'],
    featured: true,
  },
  {
    id: '6',
    slug: 'excotica-vizag',
    name: 'The Excotica Resort Vizag',
    shortName: 'Excotica Resort',
    type: 'resort',
    badge: 'Resort',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    address: 'D.no:12-7, Plot No. 431, Hospital road, VUDA Layout, Kapuluppada, Andhra Pradesh 531163',
    phone: '09059228901',
    mapsLink: 'https://maps.app.goo.gl/U8EPj9szAK3qQDnR7',
    mapEmbed: 'https://maps.google.com/maps?q=Excotica+Resort+Vizag+Kapuluppada&output=embed',
    rating: 4.2,
    reviews: 195,
    description: 'A vibrant resort experience with DJ, Rain Dance, Garden, and Private Pool Villas.',
    longDescription: 'The Excotica Resort Vizag is a one-of-a-kind resort destination near Visakhapatnam offering DJ nights, Rain Dance, lush garden spaces, dining hall, kitchen facilities, and exclusive private pool villas. Perfect for family gatherings, celebrations, and weekend getaways.',
    checkIn: '12:00 PM',
    checkOut: '11:00 AM',
    highlights: ['DJ Nights', 'Rain Dance', 'Private Pool Villa', 'Garden', 'Dining Hall', 'Kitchen'],
    amenities: ['DJ', 'Rain Dance', 'Garden', 'Dining Hall', 'Kitchen', 'Private Pool Villa', 'Room Service', 'Housekeeping', 'CCTV', 'Parking', 'Air Conditioning', 'Wi-Fi'],
    rooms: [
      {
        id: 'exo-001',
        name: 'Classic Non-AC Room',
        size: '200 sq.ft',
        view: 'Garden View',
        beds: '1 Double Bed',
        bathrooms: 1,
        price: 1278,
        maxGuests: 2,
        amenities: ['Fan', 'Hot & Cold Water', 'Toiletries', 'Housekeeping'],
        description: 'Classic room without pool access, garden view.',
        images: ['/images/hotels/excotica/room1.jpg'],
      },
      {
        id: 'exo-002',
        name: 'Family AC Room',
        size: '300 sq.ft',
        view: 'Garden View',
        beds: '2 Double Beds',
        bathrooms: 1,
        price: 1917,
        maxGuests: 4,
        amenities: ['Air Conditioning', 'TV', 'Hot & Cold Water', 'Toiletries', 'Housekeeping', 'Wi-Fi'],
        description: 'Spacious family AC room, garden view, without pool.',
        images: ['/images/hotels/excotica/room2.jpg'],
      },
      {
        id: 'exo-003',
        name: 'Private Pool Villa',
        size: '500 sq.ft',
        view: 'Pool View',
        beds: '1 King Bed',
        bathrooms: 2,
        price: 5112,
        maxGuests: 3,
        amenities: ['Private Pool', 'Air Conditioning', 'TV', 'Minibar', 'Hot & Cold Water', 'Toiletries', 'Housekeeping', 'Wi-Fi', 'Room Service'],
        description: 'Exclusive private pool villa — the ultimate resort experience.',
        images: ['/images/hotels/excotica/room3.jpg'],
      },
    ],
    images: ['/images/hotels/excotica/hotel1.jpg', '/images/hotels/excotica/hotel2.jpg'],
    featured: true,
  },
  {
    id: '7',
    slug: 'vintage-villa-kakinada',
    name: 'Hotel Vintage Villa Kakinada',
    shortName: 'Vintage Villa',
    type: 'villa',
    badge: 'Villa',
    city: 'Kakinada',
    state: 'Andhra Pradesh',
    address: 'Door No: 70, 7-2/3D, Rd Number 4, near RTO Office Junction, Siddartha Nagar, Kakinada, Ramanayyapeta, Andhra Pradesh 533003',
    phone: '08125343888',
    mapsLink: 'https://maps.app.goo.gl/3rYNKy8KeaoRoobp9',
    mapEmbed: 'https://maps.google.com/maps?q=Hotel+Vintage+Villa+Kakinada&output=embed',
    rating: 4.0,
    reviews: 156,
    description: 'Service apartment-style villa with hall, kitchen, dining and 2 AC rooms near RTO Office.',
    longDescription: 'Hotel Vintage Villa Kakinada offers a premium service apartment experience near the RTO Office in Siddartha Nagar. Features a full hall, kitchen, dining area, and two well-appointed AC bedrooms — perfect for families and extended stays.',
    checkIn: '12:00 PM',
    checkOut: '11:00 AM',
    highlights: ['Service Apartment Style', 'Full Kitchen', 'Hall + Dining', '2 AC Rooms', 'Near RTO Office', 'Family Friendly'],
    amenities: ['Air Conditioning', 'Full Kitchen', 'Hall', 'Dining Area', 'Wi-Fi', 'TV', 'Hot & Cold Water', 'Housekeeping', 'CCTV', 'Parking'],
    rooms: [
      {
        id: 'vin-001',
        name: 'Premier Room with Triple Bed & Bath Tub',
        size: '300 sq.ft',
        view: 'City View',
        beds: '1 Triple Bed',
        bathrooms: 1,
        price: 1206,
        maxGuests: 3,
        amenities: ['Air Conditioning', 'Bath Tub', 'Wi-Fi', 'TV', 'Hot & Cold Water', 'Toiletries', 'Housekeeping'],
        description: 'Premier room with triple bed and luxurious bath tub.',
        images: ['/images/hotels/vintage/room1.jpg'],
      },
      {
        id: 'vin-002',
        name: 'Superior Room',
        size: '250 sq.ft',
        view: 'City View',
        beds: '1 King Bed',
        bathrooms: 1,
        price: 1206,
        maxGuests: 2,
        amenities: ['Air Conditioning', 'Wi-Fi', 'TV', 'Hot & Cold Water', 'Toiletries', 'Housekeeping'],
        description: 'Superior room with king bed and modern amenities.',
        images: ['/images/hotels/vintage/room2.jpg'],
      },
    ],
    images: ['/images/hotels/vintage/hotel1.jpg'],
    featured: false,
  },
  {
    id: '8',
    slug: 'cozy-corner-kakinada',
    name: 'Hotel Cozy Corner Kakinada',
    shortName: 'Cozy Corner',
    type: 'villa',
    badge: 'Cozy Stay',
    city: 'Kakinada',
    state: 'Andhra Pradesh',
    address: '3-18-158, 70/7-2, near RTO Office Road, Siddartha Nagar, Kakinada, Ramanayyapeta, Andhra Pradesh 533003',
    phone: '08125343888',
    mapsLink: 'https://maps.app.goo.gl/tuSJHunB3FdJAehS9',
    mapEmbed: 'https://maps.google.com/maps?q=Hotel+Cozy+Corner+Kakinada&output=embed',
    rating: 4.0,
    reviews: 98,
    description: 'Intimate and comfortable rooms near RTO Office Road in Siddartha Nagar, Kakinada.',
    longDescription: 'Hotel Cozy Corner Kakinada is located in the same compound as Vintage Villa but accessible through a different gate. Offering cozy, well-maintained rooms with triple beds and bath tubs — a perfect intimate stay.',
    checkIn: '12:00 PM',
    checkOut: '11:00 AM',
    highlights: ['Triple Bed Rooms', 'Bath Tub', 'Near RTO Office', 'Cozy & Intimate', 'AC Rooms', 'Same-day Check-in'],
    amenities: ['Air Conditioning', 'Wi-Fi', 'TV', 'Bath Tub', 'Hot & Cold Water', 'Housekeeping', 'CCTV', 'Parking'],
    rooms: [
      {
        id: 'coz-001',
        name: 'Premier Room with Triple Bed & Bath Tub',
        size: '280 sq.ft',
        view: 'City View',
        beds: '1 Triple Bed',
        bathrooms: 1,
        price: 1206,
        maxGuests: 3,
        amenities: ['Air Conditioning', 'Bath Tub', 'Wi-Fi', 'TV', 'Hot & Cold Water', 'Toiletries', 'Housekeeping'],
        description: 'Cozy premier room with triple bed and bath tub.',
        images: ['/images/hotels/cozy/room1.jpg'],
      },
      {
        id: 'coz-002',
        name: 'Superior Room',
        size: '220 sq.ft',
        view: 'City View',
        beds: '1 King Bed',
        bathrooms: 1,
        price: 1206,
        maxGuests: 2,
        amenities: ['Air Conditioning', 'Wi-Fi', 'TV', 'Hot & Cold Water', 'Toiletries', 'Housekeeping'],
        description: 'Comfortable superior room with all essential amenities.',
        images: ['/images/hotels/cozy/room2.jpg'],
      },
    ],
    images: ['/images/hotels/cozy/hotel1.jpg'],
    featured: false,
  },
  {
    id: '9',
    slug: 'central-suites-vizag',
    name: 'The Central Suites Visakhapatnam',
    shortName: 'Central Suites',
    type: 'suites',
    badge: 'Suites',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    address: 'Jothee Theatre Rd, opposite to bombay restaurant, Daba Gardens, 104 Area, Visakhapatnam, Andhra Pradesh 530004',
    phone: '08912948901',
    mapsLink: 'https://maps.app.goo.gl/Hv754BJkypaCqrZy6',
    mapEmbed: 'https://maps.google.com/maps?q=The+Central+Suites+Visakhapatnam+Daba+Gardens&output=embed',
    rating: 4.0,
    reviews: 210,
    description: 'Executive suites in the heart of Visakhapatnam at Daba Gardens opposite Bombay Restaurant.',
    longDescription: 'The Central Suites Visakhapatnam offers executive AC rooms with queen beds in the prime Daba Gardens area. Featuring air purification, interconnected rooms, smoking rooms, and modern amenities — perfectly positioned for business and leisure guests.',
    checkIn: '12:00 PM',
    checkOut: '11:00 AM',
    highlights: ['Prime Daba Gardens Location', 'Air Purifier', 'Interconnected Rooms', 'Queen Bed', 'City View', 'Free Cancellation'],
    amenities: ['Air Conditioning', 'Iron/Ironing Board', 'Air Purifier', 'Mineral Water', 'Wi-Fi', 'TV', 'Hot & Cold Water', 'Toiletries', 'Housekeeping', 'CCTV', 'Reception 24hr', 'Luggage Assistance'],
    rooms: [
      {
        id: 'cen-001',
        name: 'Executive Room AC',
        size: '200 sq.ft (19 sq.mt)',
        view: 'City View',
        beds: '1 Queen Bed',
        bathrooms: 1,
        price: 1214,
        originalPrice: 1450,
        maxGuests: 3,
        amenities: ['Air Conditioning', 'Iron/Ironing Board', 'Air Purifier', 'Mineral Water', 'TV', 'Hot & Cold Water', 'Toiletries', 'Housekeeping'],
        description: 'Executive AC room with queen bed, city view, fits up to 3 guests.',
        images: ['/images/hotels/central/room1.jpg'],
      },
    ],
    images: ['/images/hotels/central/hotel1.jpg'],
    featured: false,
  },
];

export function getHotelBySlug(slug: string): Hotel | undefined {
  return HOTELS.find((h) => h.slug === slug);
}

export function getFeaturedHotels(): Hotel[] {
  return HOTELS.filter((h) => h.featured);
}
